### ISSUE TITLE
With workshop update HLALauncher start none vr version

### ISSUE THREAD

**Issue by Skidrow68** [JetLennit/hlalauncher#1]
Should i add some command or something to get it to start right version off HL-A?

**Comment by JetLennit** [comment]
I've heard this is causing problems, I'll look into it soon. Thanks for letting me know!

**Comment by JetLennit** [comment]
Until I can get an update out, the fix for this is to add -vr to your hlalaunchoptions.txt or add it during the first run of the launcher

**Comment by JetLennit** [comment]
Should be fixed in latest version

**Comment by Skidrow68** [comment]
Thank you JetLennit.
